baseURL = 'http://cloud.lyndeno.ca/'
languageCode = 'en-us'
title = 'Lyndon Sanche'
theme = "lsanche"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[markup.highlight]
	codeFences = true
	guessSyntax = true
	h1_Lines = ""
	lineNoStart = 1
	lineNos = true
	lineNumbersInTable = true
	tabWidth = 4
	noClasses = true
	style = "dracula"
